### ISSUE TITLE
T1.txt and  T2.txt

### ISSUE THREAD

**Issue by htszh** [KeyMismatchAttackOnNewHopeRevisitedCode/Attack#1]
How to generate these two files，T1.txt and  T2.txt

**Comment by KeyMismatchAttackOnNewHopeRevisitedCode** [comment]
Hello,

the creation of the trees is described in our paper.

Jan Vacek

**Comment by KeyMismatchAttackOnNewHopeRevisitedCode** [comment]
I added the link to the paper to the README file.
